#!/bin/bash

tmp=.mm

main() {
  for file in "$@"; do
    name=$(getName "$file")
    weight=$(getWeight "$file")

    if [ ! -z "$name" ]; then
      file=$(project "$file" "$name")
    else
      name="-"
    fi

    echo -e "${weight}\t${name}\t${file}"
  done \
  | sort -g \
  | awk '{print $3}' \
  | xargs
}

project() {
  p1=$1
  name=$2
  
  f=$(basename $p1)
  d1=$(dirname $p1)
  d2=$tmp/$d1
  p2=$d2/$f
  
  filters=$(genFilters $p1 $name | xargs)
  
  mkdir -p $d2
  eval "cat $p1 | $filters" > $p2

  echo $p2
}

getName() {
  awk '
      /^#Module / {print $2; exit}
      /^#\W+Module / {print $3; exit}
  ' "$1"
}

getWeight() {
  awk '
      /^#Weight / {w=$2; exit}
      /^#\W+Weight / {w=$3; exit}
      END { if(w) {print w} else {print 10} }
  ' "$1"
}

genFilters() {
  path=$1
  name=$2
  echo "perl -pe \'s/(?<![a-zA-Z0-9\\\/])(_[a-zA-Z]+)/${name}\\\1/g\' | "
  echo "sed 's/$\(me\)/${path//\//\\\\/}/g' | "
  echo "cat"
}

main "$@"
